### ISSUE TITLE
No rule to make target `androidutils_jni.cpp', needed by `androidutils_jni.obj'

### ISSUE THREAD

**Issue by mehranmd** [Skycoder42/AndroidUtils#1]
Hello sir.
please test your plugin with latest qpm and Qt android build.
i faced several problems and couldn't fix this one: 
"No rule to make target `androidutils_jni.cpp', needed by `androidutils_jni.obj'"
i wonder if i did something wrong.
problems was mostly because your wrapper couldn't find the androidnative file.

**Comment by Skycoder42** [comment]
Did you adjust this line: https://github.com/Skycoder42/AndroidUtils/blob/master/de_skycoder42_androidutils.prc#L13

You have to comment the lower one and uncomment the upper when using qpm. However, the "no rule to make target" error seems strange. Please upload the full buildlog, as well as the generated makefile, so I can find out whats going on

**Comment by mehranmd** [comment]
sry for the delay.
i was working on other project for a while.
i start listing the problem that i faced and the solutions i found.

1_
PROBLEM:
QMAKE error:
Cannot read C:/Users/MeHrAnM.D/Desktop/Workshop/androidTestLab/utilTest/utilTest/vendor/android/native/pri/examples/androidnativeexample/.pri: No such file or directory

FIX: change line 8 of vendor.pri from:
include($$PWD/android\native\pri\examples\androidnativeexample\\.pri)
to
include($$PWD/android\native\pri\examples\androidnativeexample\deployment.pri)

2_
compiler error:
..\utilTest\vendor\de\skycoder42\androidutils\androidutils.cpp:5:30: fatal error: systemdispatcher.h: No such file or directory
 #include <systemdispatcher.h>
                              ^
FIX: 
we need to use related path address because compiler couldn't find the file. 
in files : 
sharedpreferences.cpp
filechooser.cpp
androidutils.cpp
change #include <systemdispatcher.h> to
#include <./android/native/pri/cpp/AndroidNative/systemdispatcher.h>

last Fix will lead to : 
:-1: error: No rule to make target `androidutils_jni.cpp', needed by `androidutils_jni.obj'.  Stop.

**Comment by Skycoder42** [comment]
That still wont help me to locate the *current* error. I need the generated `Makefile` you can find the the build folder of the project. Simply upload it here as file attachment please.

Also, I have mostly abandoned this project in favor of https://github.com/Skycoder42/AndroidContentDevice and https://github.com/Skycoder42/QtMvvm, so don't expect any fixes/updates from my side. I will help you find a solution to this problem, and I do accept pull requests with fixes, if you get a working version.

**Comment by mehranmd** [comment]
> You have to comment the lower one and uncomment the upper when using qpm.

i did that too before applying fix for number 2

**Comment by mehranmd** [comment]
> I need the generated `Makefile` you can find the the build folder of the project. Simply upload it here as file attachment please.

[Makefile.zip](https://github.com/Skycoder42/AndroidUtils/files/2966083/Makefile.zip)

**Comment by Skycoder42** [comment]
Try changing this line: https://github.com/Skycoder42/AndroidUtils/blob/master/de_skycoder42_androidutils.prc#L11

To:
```
!noJniOnLoad: SOURCES += $$PWD/androidutils_jni.cpp
```

**Comment by Skycoder42** [comment]
Do you need any additional help? If not, I am going to close this issue
